### PR TITLE
Added an exception being thrown when you make a wrong api call avoidi…

### PR DESCRIPTION
**Pull request by gouaille**
…ng empty object being returned.

### CODE REVIEW

**Comment by ZzAntares** [comment]
Seems that Proxmox returns other status codes other than 200, when doing a wrong api call you should get a 4xx error if you could change this `if($response->getStatusCode() != "200")` to something like `if($response->getStatusCode() >= 400)` or other code to avoid triggering the exception even when you get a *201 created*

**Comment by gouaille** [comment]
done :-)

**Comment by ZzAntares** [comment]
Ok thanks, but somehow your change is breaking the build: https://travis-ci.org/ZzAntares/ProxmoxVE/pull_requests

Please fix it then I'll merge your commits.

**Comment by ZzAntares** [comment]
Haven't heard from you, so closing pull request.

**Pull request closed without merging**
