### PR TITLE
Guzzle Update

### PR DESCRIPTION
**Pull request by arleslie**
Would be nice for this to get merged in.
(I haven't tested it but guzzle is pretty good with backwards compatibility)

### CODE REVIEW

**Comment by ZzAntares** [comment]
Thanks! looks good but I can't merge this in `master`, please do the PR to the develop branch.

**Comment by arleslie** [comment]
@ZzAntares Sorry it took me a while, I didn't see the notification for this and just happened to look back here. :grinning:

**Comment by arleslie** [comment]
When I get some time, I'll see about adding Guzzle 6 support.

**Comment by ZzAntares** [comment]
Hi @arleslie, no problem, now this change ins conflicting, and now I remember, some time ago we planned to update guzzle to v6 in issue #6. We only needed to test it, and I've done that is working fine.

So no need to have guzzle v5, so I guess is ok to close this PR. If you have problems with the library please feel free to open up a new issue or comment it here.

Thanks!

**Comment by arleslie** [comment]
If you need another tester for v6 let me know. I'm actively using this
package for a SaaS company and I'd be happy to test it for you.

**Pull request closed without merging**
